### ISSUE TITLE
feat: Audio-to-text image caption search using embedding models [showcase]

### ISSUE THREAD

**Issue by ndrean** [dwyl/image-classifier#18]
Once you implement a db that saves the URL and caption, you can  easily add a full-text search to render all the images that contain a text input. For simplicity, use SQLite. 🔍 

You can go a step further with ML models: speech-to-text, embeddings and semantic search. You transcribe an audio input into text, and use ML (Semantic search) to render matching images. 🗣️

**Comment by ndrean** [comment]
About this: I want to query to get all my pictures for a given subject. You make an audio to query them.

0) produce a description from an image is "easy"

1) capture the audio and transcript it into text is "more or less" easy (the Javascript is not straightforward). But it work well.

Then, I want to extract or compare image captions (saved in the database) to the audio query text transcript.

- extract keyword: the [NER](https://hexdocs.pm/bumblebee/examples.html#named-entity-recognition) does not work since there is no real entity when you do a general search. The models are trained for specific keyword finding, such as location, names etc

- I went to some similarity search, meaning a nearest neighbour search (distance between embeddings). Not working - yet -  with <https://github.com/elixir-nx/hnswlib>.

**Comment by ndrean** [comment]
A bit of reading: <https://www.elastic.co/what-is/vector-search>

<img width="1376" alt="Screenshot 2023-11-25 at 16 03 52" src="https://github.com/dwyl/image-classifier/assets/6793008/51803f52-987e-4878-9f32-20304ca88bf8">

**Comment by ndrean** [comment]
Use de native browser MediaStream Record API and return a WAV file (in mono audoi/pcm format) to feed Bumblebee Whisper with the model "openai/whisper-small". 

You `allow_upload(:speech,  accept: ~w(audio/wav), auto_upload: true, progress: &handle_progress/3)`.

The Javascript hook below is attached to a button to toggle on/off audio recording. The most simple way to produce a WAV file is to use <https://github.com/mattdiamond/Recorderjs/blob/master/src/recorder.js>. Copy/paste this file and put it into the /assets/vendor" folder. You also add a dependency <https://github.com/mohayonao/inline-worker/blob/master/index.js>: copy/paste it as well, and add `var global = window` (it will fail otherwise).

```js
import Recorder from "../vendor/recorder.js";

export default {
  mounted() {
    let recorder = null,
      isRecording = false,
      recordButton = document.getElementById("record"),
      audioElement = document.getElementById("audio");

    recordButton.addEventListener("click", toggleRecording);

    function toggleRecording() {
      if (isRecording) {
        stopRecording();
      } else {
        startRecording();
      }
    }

    async function startRecording() {
      return navigator.mediaDevices
        .getUserMedia({ audio: true })
        .then((stream) => {
          let audioContext = new AudioContext();
          let input = audioContext.createMediaStreamSource(stream);
          recorder = new Recorder(input);
          recorder.record();

          isRecording = true;
          recordButton.classList.remove("bg-blue-500", "hover:bg-blue-700");
          recordButton.classList.add(
            "bg-green-500",
            "hover:bg-green-700",
            "animate-pulse"
          );
        });
    }

    let _this = this;

    function stopRecording() {
      if (!recorder) return;
      recorder.stop();
      recorder.exportWAV((blob) => {
        _this.upload("speech", [blob]);
        audioElement.src = URL.createObjectURL(blob);
      });

      isRecording = false;
      recordButton.classList.remove(
        "bg-green-500",
        "hover:bg-green-700",
        "animate-pulse"
      );
      recordButton.classList.add("bg-blue-500", "hover:bg-blue-700");
    }
  },
};
```

The Elixir code is copied from the documentation:

```elixir
def handle_progress(:speech, entry, socket) when entry.done? do
    IO.puts("speech--------")
    # if you auto_upload once the recording is finished, then the allow_upload
    # will use the data when declared in a handle_progress

    # see <https://hexdocs.pm/bumblebee/Bumblebee.Audio.html#speech_to_text_whisper/5-examples>
    dest =
      socket
      |> consume_uploaded_entry(entry, fn %{path: path} ->
        dest = Path.expand("priv/static/image_uploads/tmp.wav")
        :ok = File.cp!(path, dest)
        {:ok, dest}
      end)

    task =
      Task.Supervisor.async(
        App.TaskSupervisor,
        fn ->
          Nx.Serving.batched_run(Whisper, {:file, dest})
        end
      )

    {:noreply, assign(socket, audio_task: task)}
  end
```

It remains to code a `handle_info({ref, %{chunks: [%{text: text]}, socket)` to use the result of the Task.

**Comment by ndrean** [comment]
2) Embeddings and ANN.
  2.1) Produce an embedding from the I2T caption
  2.2)Produce an embedding from the S2T (audio transcription)
 with [Bumblebee.Text.text_embedding].
 

```elixir
defmodule App.TextEmbedding do
  def serving do
    embedding_model = "sentence-transformers/paraphrase-MiniLM-L6-v2"
    # model = "intfloat/e5-large"
    {:ok, model_info} = Bumblebee.load_model({:hf, embedding_model})
    {:ok, tokenizer} = Bumblebee.load_tokenizer({:hf,  embedding_model})

    serving = Bumblebee.Text.TextEmbedding.text_embedding(model_info, tokenizer)
  end
end

#Application.ex
[...]
children = [
  ...
  {Nx.Serving,
       serving: App.TextEmbedding.serving(),
       name: TextEmbedding,
       batch_size: 8,
       batch_timeout: 100
  },
]
...
```

```elixir
config :app, App.Repo,
  database: "./sqlite.db",
  pool_size: 5,
  show_sensitive_data_on_connection_error: true,
  load_extensions: [SqliteVss.loadable_path_vector0(), SqliteVss.loadable_path_vss0()]
```

Not sure yet how to run ANN.

**Comment by ndrean** [comment]
No real progress so far.

The `sqlite_vss` is a bit obscure. I imagine you save the vector into the db and this extension can compute some distance algorithm.


Here I tried [HSWNLib](https://github.com/elixir-nx/hnswlib) which seems close to Facebook's FAISS. Seems that you have a kind of database with an index. However, the documentation is **very** thin (sic). 
My interpretation (!) 
It seems you need to run a GenServer to get the "serving" and instantiate the index. I use the model "sentence-transformers/paraphrase-MiniLM-L6-v2" whose dimension is 384, so I believe(?) I should use 384 as the `dim` of the index space. For the norm, it must be a matter of experience on which one to use between the euclidean distance L2, the Manhattan distance L1 or [cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity).
When I upload an image, I compute an embedding on the caption text and  add the tensor into the index.
When I make an audio transcription, I run an embedding, get a tensor and make a `knn_query` against the index with this tensor.

Here are some results below. Not so talkative... and this does not correspond to any index that could represent the minimum of this `knn_query`.

```elixir
{:ok,
 #Nx.Tensor<
   u64[1][1]
   EXLA.Backend<host:0, 0.2015035495.2514354192.41223>
   [
     [2]
   ]
 >,
 #Nx.Tensor<
   f32[1][1]
   EXLA.Backend<host:0, 0.2015035495.2514354192.41224>
   [
     [0.18454807996749878]
   ]
 >}
```

Some code:

Launch the Embedding model and instantiate the index
```elixir
#Application
   children = [..., App.TextEmbedding, ...]

defmodule App.TextEmbedding do
  use GenServer

  def start_link(_) do
    GenServer.start_link(__MODULE__, {}, name: __MODULE__)
  end

  def init(_) do
    {:ok, %{model: _model, params: _params} = model_info} =
      Bumblebee.load_model({:hf, "sentence-transformers/paraphrase-MiniLM-L6-v2"})

    {:ok, tokenizer} =
      Bumblebee.load_tokenizer({:hf, "sentence-transformers/paraphrase-MiniLM-L6-v2"})

    {:ok, index} =
      HNSWLib.Index.new(_space = :cosine, _dim = 384, _max_elements = 200)

    {:ok, {model_info, tokenizer, index}}
  end

  def serve() do
    GenServer.call(__MODULE__, :serve)
  end

  def handle_call(:serve, _from, {model_info, tokenizer, index} = state) do
    serving = Bumblebee.Text.TextEmbedding.text_embedding(model_info, tokenizer)
    {:reply, {serving, index}, state}
  end
end
```

```elixir
#page_live.ex
def mount(_params, _session, socket) do
    {serving, index} = App.TextEmbedding.serve()
    {:ok, assign(socket, serving: serving, index: index, ...}
```

```elixir
# def handle_info({:ref, result}, %{assigns: assigns} = socket
cond do
   # return from Image-To-Text, compute embedding and then Upload into a bucket Task
   Map.get(assigns, :I2T_task_ref) == ref ->
        %{results: [%{text: label}]} = result
        %{embedding: data} = Nx.Serving.run(serving, label)
        HNSWLib.Index.add_items(index, data)
        # check the index count
        HNSWLib.Index.get_current_count(index) |> dbg()
        ...

   # return audio transcription, and compute an embedding and insert into the index 
   is_map(result) && Map.get(result, :chunks) != nil ->
        Path.expand("priv/static/image_uploads/tmp.wav")
        |> File.rm!()

        %{chunks: [%{text: text}]} = result
        with {:ok, label, distance} <- handle_knn(data, index) do
          {:ok, label, distance} |> dbg()

          {:noreply,
           assign(socket,
             transcription: String.trim(text),
             micro_off: false,
             knn_label: label,
             distance: distance
           )}
        else
```

```elixir
def handle_knn(data, index) do
    case HNSWLib.Index.get_current_count(index) do
      {:ok, 0} ->
        {:error, "no entries in index"}

      {:ok, _c} ->
        case HNSWLib.Index.knn_query(index, data, k: 1) do
          {:ok, label, distance} ->
            {:ok, label, distance}

          {:error, msg} ->
            {:error, msg}
        end
    end
  end
```

**Comment by ndrean** [comment]
So the branch where speech-and-find works 🥵:  <https://github.com/ndrean/image-classifier/tree/upload-save-db>

I changed from SQLite to Postgres, so the Full-Text-Search has to be rewritten but this is not the important point.

**Comment by LuchoTurtle** [comment]
Posting https://developers.google.com/machine-learning/clustering/similarity/measuring-similarity, which seems to details the three methods @ndrean mentioned 🚀

**Comment by ndrean** [comment]
Just an addition as I forgot: don't save the embedding, but save the current index once you decide to add the embedding into the `Index`. You then only need to query for the matching index with your found index. Furthermore, the `cosine` does not work for the embedding. So I had a first bad idea to save the embedding and use it :) ,  but when I gave `cosine` a try, I realised it would save space and just work if you work directly with indexes instead. 
What I am saying might seem total rubbish, but once you just read HNSWLib Readme (and there is nothing more to read) and think about it, you will understand immediately.

**Comment by ndrean** [comment]
To clarify a bit the process:

You want to do a semantic search: record an audio that describes an image, and find some corresponding images that you uploaded.

How to proceed?

1) First, you upload images into a bucket. You get back an URL. You analyse the image with a model to produce a description of it. This is a "captioning" process or Image-To-Text. You save the URL and caption ( a short descriptive text) into a DB.

2) You produce an audio from a speech. You transcript this audio into text with a model; This is Speech-To-Text.

3) For the semantic search, you want to find the images whose caption approximates your audio. To do this, you use embeddings: this transcripts a text into a well-thought vector space, and then you use an approximation algorithm.
For this, you can use HNSWLib. You build incrementally an Index struct from  your captions, and then run a `knn_search` on this index with the audio transcription as an input.




![semantic_search (1)](https://github.com/dwyl/image-classifier/assets/6793008/26f384b0-8d5c-423a-b80c-c3f115e4b847)

**Comment by ndrean** [comment]
As a reference, I added some comments on the library HNSWLib. My intention is:  not pedantic but clear when you can use a look-up by index and/or by embedding, and secondly why you need to normalise for `cosine` in the second case.

The Index is instanciated as in the GenServer above.


# HNSWLib

Elixir binding for the [hnswlib](https://github.com/nmslib/hnswlib) library.

Currently in development, alpha software.

## Usage

### Create an Index struct

```elixir
# working in L2-space
# other possible values are
#  `:ip` (inner product)
#  `:cosine` (cosine similarity)
iex> space = :l2
:l2
# each vector is a 2D-vec
iex> dim = 2
2
# limit the maximum elements to 200
iex> max_elements = 200
200
# create Index
iex> {:ok, index} = HNSWLib.Index.new(space, dim, max_elements)
{:ok,
 %HNSWLib.Index{
   space: :l2,
   dim: 2,
   reference: #Reference<0.2548668725.3381002243.154990>
 }}
```

### Add vectors to the Index struct

The Index struct is incrementally build.

```elixir
iex> data =
  Nx.tensor(
    [
      [42, 42],
      [43, 43],
      [0, 0],
      [200, 200],
      [200, 220]
    ],
    type: :f32
  )
#Nx.Tensor<
  f32[5][2]
  [
    [42.0, 42.0],
    [43.0, 43.0],
    [0.0, 0.0],
    [200.0, 200.0],
    [200.0, 220.0]
  ]
>
iex> HNSWLib.Index.get_current_count(index)
{:ok, 0}
iex> HNSWLib.Index.add_items(index, data)
:ok
iex> HNSWLib.Index.get_current_count(index)
{:ok, 5}
```

### Query nearest vector(s) in the index

`knn_query` returns a tuple `(:ok, labels, distances}`. The "labels" tensor contains the indices in the Index struct of the `k` closest elements. The "distances" tensor contains the corresponding distance between these closest elements and the query input.

```elixir
# query
iex> query = Nx.tensor([1, 2], type: :f32)
#Nx.Tensor<
  f32[2]
  [1.0, 2.0]
>
iex> {:ok, labels, dists} = HNSWLib.Index.knn_query(index, query)
{:ok,
 #Nx.Tensor<
   u64[1][1]
   [
     [2]
   ]
 >,
 #Nx.Tensor<
   f32[1][1]
   [
     [5.0]
   ]
 >}

iex> {:ok, labels, dists} = HNSWLib.Index.knn_query(index, query, k: 3)
{:ok,
 #Nx.Tensor<
   u64[1][3]
   [
     [2, 0, 1]
   ]
 >,
 #Nx.Tensor<
   f32[1][3]
   [
     [5.0, 3281.0, 3445.0]
   ]
 >}
```

### Save an Index to file

```elixir
iex> HNSWLib.Index.save_index(index, "my_index.bin")
:ok
```

### Load an Index from file

```elixir
iex> {:ok, saved_index} = HNSWLib.Index.load_index(space, dim, "my_index.bin")
{:ok,
 %HNSWLib.Index{
   space: :l2,
   dim: 2,
   reference: #Reference<0.2105700569.2629697564.236704>
 }}
iex> HNSWLib.Index.get_current_count(saved_index)
{:ok, 5}
iex> {:ok, data} = HNSWLib.Index.get_items(saved_index, [2, 0, 1])
{:ok,
 [
   <<0, 0, 0, 0, 0, 0, 0, 0>>,
   <<0, 0, 40, 66, 0, 0, 40, 66>>,
   <<0, 0, 44, 66, 0, 0, 44, 66>>
 ]}
iex> tensors = Nx.stack(Enum.map(data, fn d -> Nx.from_binary(d, :f32) end))
#Nx.Tensor<
  f32[3][2]
  [
    [0.0, 0.0],
    [42.0, 42.0],
    [43.0, 43.0]
  ]
>
```

### How to use `knn_query`

If you add a single vector to the Index struct at a time, you can save just the current index count. With the response of `knn_query`, you can then look up for the closest elements.

```elixir
:ok  = HNSWLib.Index.add_items(index, normed_data)
{:ok, idx}  =  HNSWLib.Index.get_current_count(index)
App.Repo.insert(%Data{}, idx: idx)
:ok =  HNSWLib.Index.save_index(index, saved_index)
```

If you add multiple vectors to the Index struct, it is a batch process so you can only look up with the embeddings. Then use `get_items` as above and transform the binaries to embeddings for your look up.

When you endow the vector space with the `cosine` distance, you need to normalise the embeddings (see note below)

#### Example

Suppose you have an `Nx.Serving` that runs a model. You get embeddings, save them and build your Index struct with them.

```elixir
# you get an embedding
%{embedding: data} =
    Nx.Serving.run(my_serving(), input)
# you normalise the embedding
data =
    Nx.divide(data, Nx.LinAlg.norm(data))
# you save the embedding for the look up
{:ok, _input} =
    App.Input.save(%Input{}, %{embedding: data})
# you build your Index struct
:ok = HNSWLib.Index.add_items(index, data)
HNSWLib.Index.save_index(index, "my_index.bin")
```

You run a `knn_query` with a given embedding (from the same serving) for the closest element.

```elixir
# you normalise your query data
%{embedding: query_data} =
    Nx.Serving.run(my_serving(), input_embedding)

query_data =
    Nx.divide(query_data, Nx.LinAlg.norm(query_data))
{:ok, labels, _d} =
    HNSWLib.Index.knn_query(index, query_data, k: 1)

{:ok, data} = HNSWLib.Index.get_items(index, Nx.to_flat_list(labels[0]))

t =
    data
    |> Enum.map(fn d -> Nx.from_binary(d, :f32) end)
    |> Nx.stack()

App.Input.get_by(%{embedding: t})
```

## Installation

If [available in Hex](https://hex.pm/docs/publish), the package can be installed
by adding `hnswlib` to your list of dependencies in `mix.exs`:

```elixir
def deps do
  [
    {:hnswlib, "~> 0.1.0"}
  ]
end
```

Documentation can be generated with [ExDoc](https://github.com/elixir-lang/ex_doc)
and published on [HexDocs](https://hexdocs.pm). Once published, the docs can
be found at <https://hexdocs.pm/hnswlib>.

### Notes on vector spaces

A vector space of embeddings can be equiped with an (euclidean) _inner product_. If $u=(u_1,\dots,u_n)$ and $v=(v_1,\dots,v_n)$ are two embeddings with their coordinates, the (euclidean) inner product is defined as:

$<u,v>=u_1v_1+\cdots+u_nv_n$

This inner product induces an euclidean _norm_:

$||u|| = \sqrt{<u,u>} = \sqrt{u_1^2+\cdots+u_n^2}$

Let $u_v$ be the perpendicular projection of $u$ on $v$. Then:

$<u, v> = <u_v,v> = ||u||\cdot ||v|| \cos\widehat{u,v}$

The value below is known as the _cosine similarity_.

$<\frac{u}{||u||}\frac{v}{\||v||}> = \cos\widehat{u,v}$.

Remark that the norm of the new embedding $\frac1{||u||}u$ is 1. We say that the embedding is $L_2$-normalised.

The previous formula shows that the inner product of normalised (aka unit) embeddings is the `cosine` of the angle between these "normalised" embeddings.

Source: <https://en.wikipedia.org/wiki/Cosine_similarity>

_Note that this is not a distance._

The norm in turn induces a _distance_:
$d(u,v) = ||u-v||$

By definition,  
$||u-v||^2  = <u-v,u-v>$.
so by developping, we obtain:
$||u-v||^2  = ||u||^2+||v||^2-2<u,v>$

Consider now two normalised vectors. We have:
$\frac12||u-v||^2=1-\cos\widehat{u,v} = d_c(u,v)$

This is commonly known as the "cosine distance" _when the embeddings are normalised_. It ranges from 0 to 2. Note that it is a true distance metric.

Finally, note that since we are dealing with finite dimensional vector spaces, all the norms are equivalent (in some precise mathematical way). This means that the limit points are always the same. However, note that this is not a distance (mathematically speaking).the values of the distances can be quite different, and a "clusterisation" processes can give significatively different results. The first hint for which norm to choose is to take the norm used to train the model.

**Comment by LuchoTurtle** [comment]
Closing with the merging of #47
