### ISSUE TITLE
Feat: Intro `GIF`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#21]
At present there are no `GIFs` in the `README`! 😮 
Let's fix that by creating an intro/demo `GIF` showcasing uploading + classifying a few (3-5) images.

+ [x] Simplify+focus the layout of the landing page of the app: #7 
+ [x] Use the _example_ images selected for https://github.com/dwyl/image-classifier/issues/7 as the demo images.
i.e. find 3-5 good images on `unsplash` (or other "_free_" image service), download them to your `localhost` and prepare the stage for uploading them to the _hosted_ (or `localhost`) version of `imgai`.

+ [x] Record a your desktop using `QuickTime` 
+ [x] Edit the recording to remove any unnecessary frames.
+ [x] Speed-up the upload and "spinner" to make it near-instant.
+ [x] Export the video 
+ [x] Upload to https://ezgif.com/video-to-gif to create a `GIF` from the video. 

This is a good training exercise in using [`DaVinci Resolve`](https://github.com/dwyl/studio/issues/52) for a _mini-project_. The _next_ one will be a bit longer ... 😉

**Comment by LuchoTurtle** [comment]
I'll give this a look after finishing the rest of the issues.
