### ISSUE TITLE
Feat: Store Metadata and Image Classification/Info

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-classifier#3]
As discussed on standup this morning, the app you have built in #2 doesn't currently store any data. 
This is ok for a basic demo but we want to take this a bit further. 

Please let me know when you have a few mins to discuss a potential schema for the data we can store.

I'm thinking the _minimum_ should be:

+ [x] `url` - the image that was uploaded (preferably to [`b2`](https://github.com/dwyl/imgup/issues/98) but `S3` for now ideally using the `imgup` **`API`**...) 
+ [x] `height` - the height in pixels of the image
+ [x] `width` - the width in pixels of the image
+ [x] `info` - the `String` describing the image
+ [x] `person_id` - optional for now. but eventually required if there is too much spam.

For analytics (and spam prevention) purposes, we should also have an `agent` table similar to `Hits` where User Agent (Browser/Device) is stored: [`/lib/hits/useragent.ex#L6-L8`](https://github.com/dwyl/hits/blob/a9472e78b9c8d9db1c49cc46bf61ddfc7d68e7b5/lib/hits/useragent.ex#L6-L8)

+ [x] What `else`?

**Comment by nelsonic** [comment]
As noted by @ndrean in #18 an `SQLite` DB is a good idea for this project given that the machine already has an attached `Volume`. 💭 Please time-box exploring this to `T2h` and if it's too much effort, use a `Postgres` instance with auto-shutdown.

**Comment by LuchoTurtle** [comment]
I'll start once I'm finished refactoring the models managing system and it's deployed to `fly.io`.

**Comment by nelsonic** [comment]
Sweet! 🍭 
Looking forward to it. LMK if/how I can help. 👌
