### ISSUE TITLE
Error deploying due to `toastify-js`

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/image-classifier#36]
More context in https://github.com/dwyl/image-classifier/actions/runs/7260046156/job/19778403428.

The deploy script is not working because of `toastify-js`.

**Comment by ndrean** [comment]
Probably stupid question: did you run `pnpm add toastifyjs`? in the assets?

**Comment by LuchoTurtle** [comment]
I did, which is why this is strange. This fails when running [`mix assets.deploy`](https://github.com/dwyl/image-classifier/actions/runs/7260046156/job/19778403428#step:4:1299), which works on my computer O.o

`toastify` is in the `package.json`, as per https://github.com/dwyl/image-classifier/blob/b8507c27d9100bffd9f5723edd82b71ea624cd62/assets/package.json#L3. 

Weird stuff...

I'll take a look at it once I finish #31

**Comment by ndrean** [comment]
Package.json and node_modules yes. I added it, imported it in App.js, and don't get a warning with mix phx.server nor assets.deploy (locally). I did not try running the app locally as a Docker image though.

Check the version in "config.exs"? Yours is "0.14.41", and the update is version: "0.18.6",

**Comment by ndrean** [comment]
Update your version to "0.18.6" and use `pnpm` instead of `npm` (it's full of bugs, really). I ran your code and had the same pb as you. 
Once you have pnpm installed, run in /assets `pnpm add toastify-js`. That's it.

**Comment by LuchoTurtle** [comment]
Re-opening due to https://github.com/dwyl/image-classifier/actions/runs/7337724552/job/19979080975.
