### ISSUE TITLE
Not an issue but enable Github discussions?

### ISSUE THREAD

**Issue by ndrean** [dwyl/image-classifier#95]
Shouldn't we [enable Github discussions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) for this repo?

The idea is to centralise things related (more or less) to this repo and ML in Elixir, rather than raising an issue? (and close this one by the way😀)

For example, this could be a place for the [(short) discussion](https://github.com/dwyl/image-classifier/issues/49) on the underlying usage of `ffmpeg` in Bumblebee. Instead of opening an issue

or for the remark on using [httpstat](https://github.com/dwyl/image-classifier/issues/46) to check start-up times.

For example, this could be also a place for an [example of live image recognition using webrtc](https://github.com/elixir-webrtc/reco): 
[<img width="933" alt="Screenshot 2024-03-29 at 12 50 04" src="https://github.com/dwyl/image-classifier/assets/6793008/76377435-fad1-43c9-b05d-8bf155ae5fdc">](https://www.youtube.com/watch?v=v6cMqZl8BDA)

or for an example of object detection and [`ONNX`](https://github.com/onnx) on how to use a non HuggingFace model. Object detection goes further than just captioning: it adds a localisation in the image.
[<img width="918" alt="Screenshot 2024-03-29 at 21 48 32" src="https://github.com/dwyl/image-classifier/assets/6793008/90e46d0b-da98-4c24-b652-f9a417fd48c5">](https://www.youtube.com/watch?v=OsxGB6MbA8o&t=23s)

[This notebook](https://github.com/elixir-nx/axon/blob/main/guides/serialization/onnx_to_axon.livemd) can be usefull to transform an `ONNX` model into `Axon`.

**Comment by LuchoTurtle** [comment]
Agreed!
Created it already so we can post ideas there so they're crawlable on the web and keep the issues contained :) 

https://github.com/dwyl/image-classifier/discussions
