### ISSUE TITLE
the fly app fails on semantic search

### ISSUE THREAD

**Issue by ndrean** [dwyl/image-classifier#97]
@LuchoTurtle 

You can record and listen to your audio but then the app fails.

What do you see in the logs?

**Comment by LuchoTurtle** [comment]
🤔 Interesting.

The logs say:

```
** (File.CopyError) could not copy from "/tmp/plug-1712-HBkh/live_view_upload-1712261800-60467101365-4" to "/app/priv/static/uploads/tmp.wave9e74be1-5567-420d-b590-51bc84d6d4e4.wav": no such file or directory
```

However, when running on localhost, it seems to be working.

I don't know if this may be related with the on-going DDOS attack on `fly.io` right now.

![image](https://github.com/dwyl/image-classifier/assets/17494745/8d22e1d4-b1ac-4816-b2a7-fa09139c20af)

**Comment by LuchoTurtle** [comment]
@nelsonic while on the topic, I think we should turn off the machine indefinitely. There's a higher volume of requests and having it running (even with the volume not redownloading optimization) is costing a fair amount of money. People can run it on `localhost` for themselves.

**Comment by ndrean** [comment]
I was also really wondering about the costs of running models on GPUs......Good to know

Some thoughts about the error:

```bash
"/app/priv/static/uploads/tmp.wav34a10671-5ec5-49c1-84b6-3439a10e044f.wav": no such file or directory
```

1) The failing line is 217 in "page_live.ex":
<https://github.com/ndrean/image-classifier/blob/00a5b6183bb7ab6ee888d2b80d6750a954065e41/lib/app_web/live/page_live.ex#L218>

Maybe the format "tmp.wavuuid.wav" gives some trouble to the underlying OS????

This is because I set:
```elixir
#page_live.ex
@tmp_wav Path.expand("priv/static/uploads/tmp.wav").....line 24
# set it in this assigns line 48
# use it line 217
tmp_wav = assigns.tmp_wav <> Ecto.UUID.generate() <> ".wav"
:ok = File.cp!(path, tmp_wav)
```

Maybe you can try with:
```elixir
- @tmp_wav Path.expand("priv/static/uploads/tmp.wav").....line 24
+ @tmp_wav Path.expand("priv/static/uploads/tmp").....line 24
```


2) no directory:
There is a check_or_create line   ` :ok = File.mkdir_p!(@upload_dir)` in the module `App.KnnIndex` at line 23.

**Comment by nelsonic** [comment]
@ndrean if you're curious how much it costs, see the invoice: https://github.com/dwyl/image-classifier/issues/98 💸

**Comment by LuchoTurtle** [comment]
@ndrean shouldn't be OS-related at all since it has been working for the past two weeks just fine 🤔 . It's hard to not associate it with the DDOS attack that happened yesterday. Further latency probably made it so the audio file was not properly created

**Comment by ndrean** [comment]
@LuchoTurtle 
I just tested it live yesterday, so I thought the mistake (?) was mine. So good to know it worked.

**Comment by ndrean** [comment]
So we should close this one!
